---
name: Message Chat
on:
  workflow_dispatch:
    inputs:
      chat_message:
        description: 'Message to send'
        required: true
        type: string

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Google Chat Notification
        run: |
            curl --location --request POST '${{ secrets.RELEASE_WEBHOOK }}&threadKey=${{ github.event.repository.name }}-release' \
            --header 'Content-Type: application/json' \
            --data-raw '{"text": "${{ inputs.chat_message }}"}'
